# Overall filter
odom_frame_id: "odom"
odom_model_type: "diff-corrected"
base_frame_id: "robot_footprint"
global_frame_id: "map"

min_particles: 500
max_particles: 2500
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
update_min_d: 0.2  # Default: 0.2 m
update_min_a: 0.2  # Default: 0.52 radians
recovery_alpha_slow: 0  # Default: 0
recovery_alpha_fast: 0  # Default: 0
transform_tolerance: 0.5
kld_err: 0.02
resample_interval: 2  # Default: 2

odom_alpha1: 0.5  # Default: 0.2
odom_alpha2: 0.3  # Default: 0.2
odom_alpha3: 0.5  # Default: 0.2
odom_alpha4: 0.3  # Default: 0.2

# Laser
laser_min_range: -1
laser_max_range: -1
laser_max_beams: 30
laser_z_hit: 0.95 # 0.95  # Laser beams hits obstacle (good for un-dynamic environments)
laser_z_rand: 0.05 #0.05  # Uniform distribution for unmodelled detections

# use_map_topic: true
tf_broadcast: true